# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set environment variables if you want
ENV MONGO_INITDB_ROOT_USERNAME=Pasupathikumar
ENV MONGO_INITDB_ROOT_PASSWORD=Pasupathikumar1234
ENV MONGO_INITDB_DATABASE=Postil-DB

# Expose MongoDB port
EXPOSE 27017

# Default command to run MongoDB
CMD ["mongod"]
